var $formElement = $("form");
var $cityInput = $("#city");
var $stateInput = $("#state");
var $page1Element = $(".page-1");
var $headerElement = $("header > h2");
var $eventsTable = $(".events-table > tbody");
var $breweryTable = $(".brewery-table > tbody");
var $page2Element = $(".page-2");
var $eventsModal = $(".events-modal");
var $breweriesModal = $(".breweries-modal");
var $eventsModalButton = $(".events-modal button");
var $breweriesModalButton = $(".breweries-modal button");
var modals = new Modals($eventsModal, $eventsModalButton, $breweriesModal, $breweriesModalButton);
var display = new Display($headerElement, $eventsTable, $breweryTable, $page2Element);
var form = new Form($formElement, $cityInput, $stateInput, $page1Element);
var app = new App(form, display, modals);
app.start();
fillSelect(stateCodes);
